### ISSUE TITLE
MacOS : resource

### ISSUE THREAD

**Issue by t-kimber** [pharmai/plip#88]
**Describe the bug**
Following error when running the example from the README (`my_mol.load_pdb('/tmp/1EVE.pdb') `)
`NameError: name 'resource' is not defined`

**To Reproduce**
1. Run the example on README
2. See error `NameError: name 'resource' is not defined`

**Expected behavior**
`print(my_mol) # Shows name of structure and ligand binding sites`

**Screenshots**

![image](https://user-images.githubusercontent.com/31308592/100369983-e59a5a80-3005-11eb-8ee9-460c0a42abd7.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7 
 - Browser: chrome

**Additional context**
`resource`for Mac https://github.com/pharmai/plip/blob/61a4bc986c2bad7d490501b2529bc823605fc248/plip/basic/supplemental.py#L21

**Comment by fkaiserbio** [comment]
Dear t-kimber,

could you please tell me how you installed PLIP and its dependencies, especially OpenBabel? I see from your logs that you run in a miniconda environment.

Thanks!

**Comment by t-kimber** [comment]
Thanks @fkaiserbio for your answer.
I use conda-forge for both, more specifically:

`openbabel                 3.1.1            py38hc545d94_1    conda-forge`

`plip                      2.1.6              pyhd8ed1ab_0    conda-forge`

**Comment by CoryKornowicz** [comment]
@fkaiserbio I am also having this same issue. However, I am interested if we can just use trajectory data instead of a single pdb frame to make it faster.

**Comment by CoryKornowicz** [comment]
I created a pull request to fix the issue on Mac's. It is hacky at the moment; however, once openbabel is installed separately using the python bindings CMake flag, plip can be installed without searching for it as a requirement allowing the install to succeed. The resource issue is fixed by simply deleting it. I don't believe it is needed in this day and age. (I could be wrong, but no problems so far)

**Comment by fkaiserbio** [comment]
Thanks for submitting the PR, this should be fixed in c61e8d9539f19da93fe175ce4a567adc844d78cc.

I decided not to remove the requirement for now. The manual installation of OpenBabel was a long debated issue, but it is explicitly stated on the front page README. You might also consider using the Docker image.

**Comment by t-kimber** [comment]
A possible work around without installing OpenBabel from source, but from conda is to use the following in your conda environment: 
`pip install -U https://github.com/pharmai/plip/archive/development.tar.gz --no-deps`

![example_plip](https://user-images.githubusercontent.com/31308592/101187171-51a73f00-3654-11eb-9be4-b89d3c02a6c5.png)
