### ISSUE TITLE
Visualizations faulty for models other than model 1

### ISSUE THREAD

**Issue by kalinni** [pharmai/plip#89]
**Describe the bug**
Visualizations are not working properly when using the model-flag to chose other models than the first one. Looks like only the ligand and interactions within the ligand are displayed. However, the report lists all interactions we'd expect.

**To Reproduce**
Run plip with --model 2 e.g. for pdb structure 6G99

**Desktop (please complete the following information):**
- OS: Windows 10
- pymol version 2.4
- plip Version 2.1.6 plus the changes to get the model flag working

Sarah encounters the issue on Ubuntu 18.04.4 LTS too, so it's not Windows specific. She is running pymol 2.2.

**Additional context**
I tried figuring out the issue myself, but wasn't able to solve it so far. I'm not at home enough in the plip code and also with pymol yet I guess. :D I thought it might be neccessary to also specify the model in the visualization process at some point. I played around with cmd.frame(n) but to no avail...

**Comment by fkaiserbio** [comment]
Thank you for reporting that issue. I had a look and it seems that this is not quickly to solve due to numbering offsets that occur with the current PDB parsing routine. Please circumvent the issue for now by writing the model you want to a new PDB file before passing it over to PLIP. We will add the issue to our backlog and fix it when we have capacity.

**Comment by fkaiserbio** [comment]
After looking again on it, I was able to fix it quicker than expected. PLIP renumbers atoms for unknown historic reasons (which should be dropped by the way) and thus the atoms selected for visualization had a offset. This was not an issue for the first model, but affected all subsequent ones. Fixed in `development` commit f6adff99790d76ef2efeef0fd4c1d55e3fbab12b.

**Comment by ssalentin** [comment]
If I remember correctly, the renumbering is needed for correctly handling numbering in PDB structures with TER records. Would be worth checking some of those structures before removing the renumbering code. Might also be that this became obsolete with newer versions of OpenBabel.

**Comment by fkaiserbio** [comment]
@ssalentin Thanks for detailing the background :+1:
