### ISSUE TITLE
--intra option not working for all structures

### ISSUE THREAD

**Issue by kalinni** [pharmai/plip#90]
**Describe the bug**
I integrated the --intra option in the soon to be released new version of the web tool and just randomly tested it for some structrues. For many it works but not so for 1EVE. It starts running but at some point stops without generating any error messages and without creating any files but the downloaded pdb file.

**To Reproduce**
Run plip for 1EVE with option --intra A

**Screenshots**
![grafik](https://user-images.githubusercontent.com/9887347/100450492-07531a80-30b6-11eb-8c3d-17d1f9407937.png)

The --maxthread 1 option I use because I'm in a conda environment and more threads cause issues there somehow...

**Desktop (please complete the following information):**
 - OS: Windows 10
 - plip Version 2.1.6

**Comment by fkaiserbio** [comment]
I think you are running in some resource issues here. Maybe because of the conda environment and weak hardware. It seems that your Python interpreter silently dies in the background. The way how intra-detection is implemented in PLIP scales basically `n^2`. `1eve` is a pretty large structure of >500 amino acids and approx. 5000 atoms
[1eve.zip](https://github.com/pharmai/plip/files/5617415/1eve.zip)
. So it takes a long time to be processed by PLIP. One would need to optimize the way how intra detection works. I can easily calculate the structure on my laptop, although it takes a few minutes:

```
$ docker run --rm \
    -v ${PWD}:/results \
    -w /results \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    pharmai/plip:latest -i 1eve -yv --intra A
```

See the results and logs in the attached ZIP file. And thank you for your detailed and easy to follow report! :+1: 

Best
Florian
